import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Inter,
  Lato,
  Montserrat,
  Oswald,
  Poppins,
  Raleway,
} from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  weight: ["100", "200", "300", "500", "700"],
  subsets: ["greek"],
});
const raleway = Raleway({
  variable: "--font-raleway",
  weight: ["100", "200", "300", "500", "700"],
  subsets: ["cyrillic", "cyrillic-ext", "latin", "latin-ext", "vietnamese"],
});
const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "500", "700"],
  subsets: ["latin", "latin-ext"],
});
const montserrat = Montserrat({
  variable: "--font-montserrat",
  weight: ["100", "200", "300", "500", "700"],
  subsets: ["cyrillic", "cyrillic-ext", "latin", "vietnamese"],
});
const lato = Lato({
  variable: "--font-lato",
  weight: ["100", "300", "700", "900"],
  subsets: ["latin"],
  display: "swap",
});
const oswald = Oswald({
  variable: "--font-oswald",
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${montserrat.variable} ${raleway.variable} ${oswald.variable} ${poppins.variable} ${lato.variable} ${inter.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
